/**
 * Rice Management Service
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ApiArrivalsGetCollection200ResponseSearchMappingInner } from './apiArrivalsGetCollection200ResponseSearchMappingInner';


export interface ApiArrivalsGetCollection200ResponseSearch { 
    '@type'?: string;
    template?: string;
    variableRepresentation?: string;
    mapping?: Array<ApiArrivalsGetCollection200ResponseSearchMappingInner>;
}

