/**
 * Rice Management Service
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ApiArrivalsGetCollection200ResponseView { 
    '@id'?: string;
    '@type'?: string;
    first?: string;
    last?: string;
    previous?: string;
    next?: string;
}

