/**
 * Rice Management Service
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ApiArrivalsGetCollection200ResponseSearchMappingInner { 
    '@type'?: string;
    variable?: string;
    property?: string | null;
    required?: boolean;
}

