/**
 * Rice Management Service
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ApiArrivalsGetCollection200ResponseSearch } from './apiArrivalsGetCollection200ResponseSearch';
import { ClientJsonld } from './clientJsonld';
import { ApiArrivalsGetCollection200ResponseView } from './apiArrivalsGetCollection200ResponseView';


export interface ApiClientsGetCollection200Response { 
    member: Array<ClientJsonld>;
    totalItems?: number;
    view?: ApiArrivalsGetCollection200ResponseView;
    search?: ApiArrivalsGetCollection200ResponseSearch;
}

