/**
 * Rice Management Service
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 */
export interface CinCinCollectionGet { 
    locationZone?: string;
    locationRegion?: string | null;
    locationProvince?: string | null;
    country?: string | null;
}

