/**
 * Rice Management Service
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GenderManagementJsonldClientCollectionGetClientCollectionPostClientCollectionPutGenderCollectionGet } from './genderManagementJsonldClientCollectionGetClientCollectionPostClientCollectionPutGenderCollectionGet';
import { ArrivalJsonldArrivalCollectionGetArrivalCollectionPostStatusesCollectionGetStatusesCollectionPostBagCollectionGetBagCollectionPostContext } from './arrivalJsonldArrivalCollectionGetArrivalCollectionPostStatusesCollectionGetStatusesCollectionPostBagCollectionGetBagCollectionPostContext';


/**
 * Gestion des clients de notre application
 */
export interface ClientJsonldClientCollectionGetClientCollectionPostClientCollectionPutGenderCollectionGet { 
    '@context'?: ArrivalJsonldArrivalCollectionGetArrivalCollectionPostStatusesCollectionGetStatusesCollectionPostBagCollectionGetBagCollectionPostContext;
    readonly '@id'?: string;
    readonly '@type'?: string;
    readonly id?: number;
    name: string;
    lastName: string;
    cin: string;
    address: string;
    gender?: GenderManagementJsonldClientCollectionGetClientCollectionPostClientCollectionPutGenderCollectionGet | null;
    user?: string | null;
}

