/**
 * Rice Management Service
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Gestion des clients de notre application
 */
export interface ClientClientCollectionPostClientCollectionPutCinCollectionPost { 
    name: string;
    lastName: string;
    cin: string;
    address: string;
    gender?: string | null;
}

