/**
 * Rice Management Service
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GenderManagementClientCollectionGetClientCollectionPostClientCollectionPutGenderCollectionGet } from './genderManagementClientCollectionGetClientCollectionPostClientCollectionPutGenderCollectionGet';


/**
 * Gestion des clients de notre application
 */
export interface ClientClientCollectionGetClientCollectionPostClientCollectionPutGenderCollectionGet { 
    readonly id?: number;
    name: string;
    lastName: string;
    cin: string;
    address: string;
    gender?: GenderManagementClientCollectionGetClientCollectionPostClientCollectionPutGenderCollectionGet | null;
    user?: string | null;
    cin_provenance?: string | null;
}

