/**
 * Rice Management Service
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Gestion des clients de notre application
 */
export interface Client { 
    readonly id?: number;
    name: string;
    lastName: string;
    cin: string;
    address: string;
    createdAt?: string | null;
    updatedAt?: string | null;
}

