/**
 * Rice Management Service
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ArrivalJsonldArrivalCollectionGetArrivalCollectionPostStatusesCollectionGetStatusesCollectionPostBagCollectionGetBagCollectionPostContext } from './arrivalJsonldArrivalCollectionGetArrivalCollectionPostStatusesCollectionGetStatusesCollectionPostBagCollectionGetBagCollectionPostContext';
import { ICinProvenance } from './clientJsonldClientCollectionGetClientCollectionPostClientCollectionPutGenderCollectionGet';

/**
 * Gestion des clients de notre application
 */
export interface ClientJsonld {
    '@context'?: ArrivalJsonldArrivalCollectionGetArrivalCollectionPostStatusesCollectionGetStatusesCollectionPostBagCollectionGetBagCollectionPostContext;
    readonly '@id'?: string;
    readonly '@type'?: string;
    readonly id?: number;
    name: string;
    lastName: string;
    cin: string;
    address: string;
    createdAt?: string | null;
    updatedAt?: string | null;
    cin_provenance?: Array<ICinProvenance>;
}

