/**
 * Rice Management Service
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 */
export interface ContactContactCollectionPost { 
    name?: string;
    lastName?: string;
    email?: string | null;
    phoneNumber?: string | null;
}

