/**
 * Rice Management Service
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 */
export interface HistoriqueTempJsonld { 
    readonly '@id'?: string;
    readonly '@type'?: string;
    readonly id?: number;
    nomTable?: string | null;
    action?: string | null;
    details?: string | null;
    date_action?: string | null;
    dateAction?: string | null;
}

