/**
 * Rice Management Service
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface LoginCheckPost200Response {
    readonly token: string;
    readonly refreshToken: string;
}

