/**
 * Rice Management Service
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 */
export interface Stock { 
    readonly id?: number;
    aivalableQuantity?: string;
    createdAt?: string | null;
    updatedAt?: string | null;
    bags?: Array<string>;
    bag?: Array<string>;
}

