/**
 * Rice Management Service
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 */
export interface TypeCompteJsonldTypeCompteCollectionGet { 
    readonly '@id'?: string;
    readonly '@type'?: string;
    role?: string;
}

