/**
 * Rice Management Service
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 */
export interface Typerice { 
    readonly id?: number;
    riceName: string;
    description: string;
    createdAt?: string | null;
    updatedAt?: string | null;
}

