/**
 * Rice Management Service
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 */
export interface UserReadUser { 
    readonly id?: number;
    email?: string;
    /**
     * The user roles
     */
    roles?: Array<string>;
    createdAt?: string | null;
    updatedAt?: string | null;
    client?: string | null;
}

