export * from './arrival.service';
import { ArrivalService } from './arrival.service';
export * from './bag.service';
import { BagService } from './bag.service';
export * from './client.service';
import { ClientService } from './client.service';
export * from './genderManagement.service';
import { GenderManagementService } from './genderManagement.service';
export * from './historiqueTemp.service';
import { HistoriqueTempService } from './historiqueTemp.service';
export * from './loginCheck.service';
import { LoginCheckService } from './loginCheck.service';
export * from './status.service';
import { StatusService } from './status.service';
export * from './stock.service';
import { StockService } from './stock.service';
export * from './typeCompte.service';
import { TypeCompteService } from './typeCompte.service';
export * from './typerice.service';
import { TypericeService } from './typerice.service';
export * from './user.service';
import { UserService } from './user.service';
export const APIS = [ArrivalService, BagService, ClientService, GenderManagementService, HistoriqueTempService, LoginCheckService, StatusService, StockService, TypeCompteService, TypericeService, UserService];
